export const CONFIG = {
  apiPrefix: "/api",
  allowedCorsOrigins: ["tauri://localhost", "https://tauri.localhost"],
  authTokenTtlMs: 30 * 24 * 60 * 60 * 1000,
  streamUrlTtlSeconds: 5 * 60,
  rateLimitPerMinute: 60,
  userKeyPrefix: "user:",
  rateLimitKeyPrefix: "rate:",
  passwordHashPepper: "spotijay_kv",
  adminUsername: "admin",
  maxUsernameLength: 32,
  minUsernameLength: 3,
  minPasswordLength: 6,
  maxFileNameLength: 180,
  audioCacheControl: "private, max-age=300",
  jsonCacheControl: "no-store",
  healthCacheControl: "no-store",
  allowedAudioExtensions: [".m4a", ".mp3", ".wav", ".ogg", ".flac", ".aac"],
  allowedAudioMimeTypes: [
    "audio/mp4",
    "audio/x-m4a",
    "audio/mpeg",
    "audio/wav",
    "audio/ogg",
    "audio/flac",
    "audio/aac",
    "audio/x-aac",
  ],
} as const;
